---
- name: create dirs
  loop:
    - /etc/systemd/system/docker.service.d
    - /etc/docker
  file:
    path: '{{ item }}'
    state: directory
  tags:
    - docker

- name: download key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  tags:
    - docker

- name: add repository
  apt_repository:
    repo: 'deb [arch={{ docker_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    filename: docker
    update_cache: yes
    state: present
  tags:
    - docker

- name: install packages
  loop:
    - docker-ce
    - python3-docker
  package:
    name: '{{ item }}'
    state: present
  tags:
    - docker

- name: write override
  notify:
    - restart docker
  template:
    src: override.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  tags:
    - docker

- name: write daemon config
  notify:
    - restart docker
  copy:
    content: "{{ docker_daemon_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
  tags:
    - docker

- name: start service
  systemd:
    name: docker
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - docker

- name: docker login
  loop: '{{ docker_registries }}'
  loop_control:
    label: '{{ item.url }}'
  docker_login:
    registry: '{{ item.url }}'
    username: '{{ item.username }}'
    password: '{{ item.password }}'
    email: '{{ item.email | default("") }}'
    reauthorize: '{{ item.reauthorize | default("no") }}'
    state: '{{ item.state | default("present") }}'
  tags:
    - docker

...
