# Standards: 0.1
---
- name: Create required dirs
  loop:
    - /etc/systemd/system/docker.service.d
    - /etc/docker
  file:
    path: "{{ item }}"
    state: directory
  tags:
    - docker

- name: Download repo key
  when: docker_upstream_version
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  tags:
    - docker

- name: Add apt repository
  when: docker_upstream_version
  apt_repository:
    repo: "deb [arch={{ docker_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    update_cache: True
    state: present
  tags:
    - docker

- name: Install required packages
  loop:
    - "{{ 'docker-ce' if docker_upstream_version else 'docker.io' }}"
    - python3-docker
  package:
    name: "{{ item }}"
    state: present
  tags:
    - docker

- name: Write service override
  when: docker_daemon_override
  notify:
    - Restart docker
  template:
    src: override.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  tags:
    - docker

- name: Write daemon config
  notify:
    - Restart docker
  copy:
    content: "{{ docker_daemon_config | to_nice_json }}"
    dest: /etc/docker/daemon.json
  tags:
    - docker

- name: Start docker service
  systemd:
    name: docker
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - docker

- name: Create defined networks
  loop: "{{ docker_networks_general + docker_networks_extra }}"
  loop_control:
    label: "{{ item.name }}"
  docker_network:
    name: "{{ item.name }}"
    enable_ipv6: "{{ item.enable_ipv6 | default(False) }}"
    ipam_config: "{{ item.ipam_config | default([]) }}"
    force: "{{ item.force | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  tags:
    - docker

- name: Handle registry login
  loop: "{{ docker_registries }}"
  loop_control:
    label: "{{ item.url }}"
  docker_login:
    registry: "{{ item.url }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email | default('') }}"
    reauthorize: "{{ item.reauthorize | default(False) }}"
    state: "{{ item.state | default('present') }}"
  tags:
    - docker

...
